# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 23f54f1a31e2580f6ce04d0002c1a37b745280ba123b4fae81940b807644d67d0248a8512c35c4e23a724bfbf27bd11b4dc17552191f45b61360e78094e46f87

test:
  secret_key_base: 2834e30f4558004eec80b9fd05f3d9b6c3b342083d590b995087c11d46ab78002b37f03565cdcc6e104a74d3bc3c66387bd2feda3af9f81251ab4a6d0ca9fc0c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
